# Generated by Django 5.1.5 on 2025-02-23 06:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authorapp', '0001_initial'),
        ('postapp', '0002_alter_post_author'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Author',
        ),
    ]
