# Generated by Django 5.1.5 on 2025-03-06 06:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('carapp', '0002_car_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='car',
            name='user',
        ),
    ]
