# Generated by Django 5.1.5 on 2025-02-12 08:11

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='studentmodel',
            fields=[
                ('roll', models.IntegerField(primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=20)),
                ('fathername', models.CharField(max_length=30)),
                ('address', models.TextField()),
            ],
        ),
    ]
